server:
  port: 8001
  servlet:
    context-path: /member
spring:
  application:
    name: member
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.3.48/train_member?useUnicode=true&characterEncoding=utf-8&useSSL=false
    #url: jdbc:mysql://192.168.0.106/train_member?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: train_member
    password: Member123

# mybatis xml路径
mybatis:
  mapperLocations: classpath:mapper/*.xml
logging:
  level:
    com.tsuki.train.member.mapper: trace
