GET http://localhost:8002/business/hello
Accept: application/json

###

GET http://localhost:8000/business/hello
Accept: application/json

###

POST http://localhost:8000/business/admin/station/save
Content-Type: application/x-www-form-urlencoded;charset=UTF-8

name=12345678

###
POST http://localhost:8002/business/test
Content-Type: application/x-www-form-urlencoded;charset=UTF-8

name=jhg

###
POST http://localhost:8001/member/test
Content-Type: application/x-www-form-urlencoded;charset=UTF-8

name=jhg