GET http://localhost:8001/member/hello
Accept: application/json

###

GET http://localhost:8000/member/hello
Accept: application/json

###
POST http://localhost:8000/member/passenger/save
Content-Type: application/json
token: {{token}}

{
  "name": "test",
  "idCard": "123321",
  "type": "1"
}

###
POST http://localhost:8000/member/admin/sys-user/save
Content-Type: application/json
token: {{token}}

{
  "username": "test",
  "password": "123321",
  "salt": "test1",
  "email": "391190087@qq.com",
  "mobile": "143434",
  "status": "1",
  "createUserId": "1"
}
###
POST http://localhost:8000/member/admin/sys-user/login
Content-Type: application/json

{
  "username": "test",
  "password": "' or 1 = 1;--",
  "code": "123456"
}
###
POST http://localhost:8000/member/admin/sys-user/getCode
Content-Type: application/json
###

GET http://localhost:8000/member/admin/sys-user/getCode
Accept: application/json

