server:
  port: 8000
spring:
#  application:
#    name: cloud-gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations: # 允许请求来源
          '[/**]':
            allowCredentials: true # 是否允许携带cookie
            allowedHeaders: '*' # 允许携带的头信息
            allowedMethods: '*' # 允许的请求方式
            allowedOriginPatterns: '*'
            maxAge: 3600 # 跨域检测的有效期，会发起一个OPTION请求
      discovery:
        locator:
          enabled: false  #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: member #路由的ID，没有固定规则但要求唯一，建议配合服务名
          uri: http://localhost:8001   #匹配后提供服务的路由地址
          #uri: lb://cloud-payment-service
          predicates:
            - Path=/member/**   #断言,路径相匹配的进行路由

        - id: business
          uri: http://localhost:8002   #匹配后提供服务的路由地址
          #uri: lb://cloud-payment-service
          predicates:
            - Path=/business/**  #断言,路径相匹配的进行路由
            #- After=2023-08-09T21:59:19.537+08:00[GMT+08:00]

        - id: batch #路由的ID，没有固定规则但要求唯一，建议配合服务名
          uri: http://localhost:8003   #匹配后提供服务的路由地址
          #uri: lb://cloud-payment-service
          predicates:
            - Path=/batch/**   #断言,路径相匹配的进行路由