server:
  port: 8002
  servlet:
    context-path: /business

spring:
  application:
    name: business

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    #url: jdbc:mysql://192.168.3.48/train_business?useUnicode=true&characterEncoding=utf-8&useSSL=false
    url: jdbc:mysql://192.168.0.106/train_business?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: train_business
    password: Business123

# mybatis xml路径
mybatis:
  mapperLocations: classpath:mapper/*.xml
logging:
  level:
    com.tsuki.train.business.mapper: trace #com.tsuki.train.mapper为包名