server:
  port: 8003
  servlet:
    context-path: /batch
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    #url: jdbc:mysql://192.168.3.48/train_batch?useUnicode=true&characterEncoding=utf-8&useSSL=false
    url: jdbc:mysql://192.168.0.106/train_batch?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: train_batch
    password: Batch123

# mybatis xml路径
mybatis:
  mapperLocations: classpath:mapper/*.xml
logging:
  level:
    com.tsuki.train.batch.mapper: trace #com.tsuki.train.mapper为包名